"""Rename column dislike to dislikes

Revision ID: 51e3ed2f83ec
Revises: 7418a424f51b
Create Date: 2023-09-05 13:58:00.397548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e3ed2f83ec'
down_revision: Union[str, None] = '7418a424f51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.drop_column('posts', 'dislike')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislike', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'dislikes')
    # ### end Alembic commands ###
